# Generated by Django 3.2 on 2021-04-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.CharField(choices=[('0', 'All'), ('1', 'Kharkov'), ('2', 'Kiev'), ('3', 'Dnepr')], default=0, max_length=20),
        ),
    ]
