# Generated by Django 3.2 on 2021-04-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(choices=[('0', 'Все'), ('1', 'Харьков'), ('2', 'Киев'), ('3', 'Днепр')], default=0, max_length=20),
        ),
    ]
